### ISSUE TITLE
ShockWAVE Syndrome Embed Issues

### ISSUE THREAD

**Issue by Aeriqu** [Aeriqu/CroBot#5]
The new song, "* Erm, could it be a Spatiotemporal ShockWAVE Syndrome...?" does not return any data. The song does exist in the database. Reproducible within servers and in a direct message with the bot.

Most likely because of length of the title, with a length of 58. May need to check if I need to optimize the embed or see if it's a different cause.

Example:
![image](https://user-images.githubusercontent.com/4679616/66655257-5c597600-ec01-11e9-9f28-0c06a8db5b05.png)

**Comment by Aeriqu** [comment]
In this case, it most likely is a length issue.
Edit: Actually, an empty string was the cause. Discord does not appreciate an empty string for a field value.

```Traceback (most recent call last):
  File "~/CroBot/venv/lib/python3.6/site-packages/discord/client.py",
    await coro(*args, **kwargs)
  File "~/CroBot/run.py", line 30, in on_message
    await command.do(client, message)
  File "~/CroBot/command.py", line 73, in do
    await func(client, message)
  File "~/CroBot/CroBot/features/sdvxin/commands.py", line 225, in def
    await search(message)
  File "~/CroBot/CroBot/features/sdvxin/commands.py", line 265, in sea
    await message.channel.send(embed=embeds.song(song_list[0]))
  File "~/CroBot/venv/lib/python3.6/site-packages/discord/abc.py", lin
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "~/CroBot/venv/lib/python3.6/site-packages/discord/http.py", li
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In embed.fields.1.value: This field is required
Ignoring exception in on_message

**Comment by Aeriqu** [comment]
Basic commit was made and pushed to develop. Currently on the main discord bot for testing. https://github.com/Aeriqu/CroBot/commit/ccc804104696d3d38cdb1b80a6be9872535adcc3

**Comment by Aeriqu** [comment]
No issues found overnight. Completed with merge. https://github.com/Aeriqu/CroBot/commit/91b0ede00825ebee0692039e06c265cad4a01b14
